/**
 * Demo Data for Ariadne
 * 
 * Sample browsing graph data for standalone/demo mode
 * when the Chrome extension API is not available.
 */

import type { GraphNode, GraphEdge, Session, TimelineData } from '@/types';

// Generate a consistent position for nodes
const positions: Record<string, { x: number; y: number }> = {
  'tab-1': { x: 400, y: 100 },
  'tab-2': { x: 200, y: 250 },
  'tab-3': { x: 600, y: 250 },
  'tab-4': { x: 100, y: 400 },
  'tab-5': { x: 300, y: 400 },
  'tab-6': { x: 500, y: 400 },
  'tab-7': { x: 700, y: 400 },
  'tab-8': { x: 200, y: 550 },
  'tab-9': { x: 400, y: 550 },
  'tab-10': { x: 600, y: 550 },
};

export const demoNodes: GraphNode[] = [
  {
    id: 'tab-1',
    tabId: 1,
    url: 'https://google.com',
    title: 'Google Search',
    favicon: 'https://www.google.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: null,
    timestamp: Date.now() - 3600000,
    status: 'active',
    position: positions['tab-1'],
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: 'tab-2',
    tabId: 2,
    url: 'https://github.com',
    title: 'GitHub: Let\'s build from here',
    favicon: 'https://github.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-1',
    timestamp: Date.now() - 3000000,
    status: 'active',
    position: positions['tab-2'],
    createdAt: Date.now() - 3000000,
    updatedAt: Date.now() - 3000000,
  },
  {
    id: 'tab-3',
    tabId: 3,
    url: 'https://stackoverflow.com',
    title: 'Stack Overflow - Where Developers Learn',
    favicon: 'https://stackoverflow.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-1',
    timestamp: Date.now() - 2800000,
    status: 'active',
    position: positions['tab-3'],
    createdAt: Date.now() - 2800000,
    updatedAt: Date.now() - 2800000,
  },
  {
    id: 'tab-4',
    tabId: 4,
    url: 'https://github.com/features',
    title: 'GitHub Features',
    favicon: 'https://github.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-2',
    timestamp: Date.now() - 2400000,
    status: 'closed',
    position: positions['tab-4'],
    createdAt: Date.now() - 2400000,
    updatedAt: Date.now() - 2400000,
    closedAt: Date.now() - 1200000,
  },
  {
    id: 'tab-5',
    tabId: 5,
    url: 'https://github.com/pricing',
    title: 'GitHub Pricing',
    favicon: 'https://github.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-2',
    timestamp: Date.now() - 2200000,
    status: 'active',
    position: positions['tab-5'],
    createdAt: Date.now() - 2200000,
    updatedAt: Date.now() - 2200000,
  },
  {
    id: 'tab-6',
    tabId: 6,
    url: 'https://stackoverflow.com/questions',
    title: 'Newest Questions - Stack Overflow',
    favicon: 'https://stackoverflow.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-3',
    timestamp: Date.now() - 2000000,
    status: 'active',
    position: positions['tab-6'],
    createdAt: Date.now() - 2000000,
    updatedAt: Date.now() - 2000000,
  },
  {
    id: 'tab-7',
    tabId: 7,
    url: 'https://stackoverflow.com/tags',
    title: 'Tags - Stack Overflow',
    favicon: 'https://stackoverflow.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-3',
    timestamp: Date.now() - 1800000,
    status: 'closed',
    position: positions['tab-7'],
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now() - 1800000,
    closedAt: Date.now() - 900000,
  },
  {
    id: 'tab-8',
    tabId: 8,
    url: 'https://react.dev',
    title: 'React – The library for web and native user interfaces',
    favicon: 'https://react.dev/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-6',
    timestamp: Date.now() - 1500000,
    status: 'active',
    position: positions['tab-8'],
    createdAt: Date.now() - 1500000,
    updatedAt: Date.now() - 1500000,
  },
  {
    id: 'tab-9',
    tabId: 9,
    url: 'https://tailwindcss.com',
    title: 'Tailwind CSS - Rapidly build modern websites',
    favicon: 'https://tailwindcss.com/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-6',
    timestamp: Date.now() - 1200000,
    status: 'active',
    position: positions['tab-9'],
    createdAt: Date.now() - 1200000,
    updatedAt: Date.now() - 1200000,
  },
  {
    id: 'tab-10',
    tabId: 10,
    url: 'https://www.typescriptlang.org',
    title: 'TypeScript: JavaScript With Syntax For Types.',
    favicon: 'https://www.typescriptlang.org/favicon.ico',
    screenshot: null,
    windowId: 1,
    sessionId: 'demo-session',
    parentId: 'tab-8',
    timestamp: Date.now() - 600000,
    status: 'active',
    position: positions['tab-10'],
    createdAt: Date.now() - 600000,
    updatedAt: Date.now() - 600000,
  },
];

export const demoEdges: GraphEdge[] = [
  {
    id: 'edge-1-2',
    source: 'tab-1',
    target: 'tab-2',
    type: 'navigation',
    timestamp: Date.now() - 3000000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 3000000,
  },
  {
    id: 'edge-1-3',
    source: 'tab-1',
    target: 'tab-3',
    type: 'navigation',
    timestamp: Date.now() - 2800000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 2800000,
  },
  {
    id: 'edge-2-4',
    source: 'tab-2',
    target: 'tab-4',
    type: 'navigation',
    timestamp: Date.now() - 2400000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 2400000,
  },
  {
    id: 'edge-2-5',
    source: 'tab-2',
    target: 'tab-5',
    type: 'navigation',
    timestamp: Date.now() - 2200000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 2200000,
  },
  {
    id: 'edge-3-6',
    source: 'tab-3',
    target: 'tab-6',
    type: 'navigation',
    timestamp: Date.now() - 2000000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 2000000,
  },
  {
    id: 'edge-3-7',
    source: 'tab-3',
    target: 'tab-7',
    type: 'navigation',
    timestamp: Date.now() - 1800000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'edge-6-8',
    source: 'tab-6',
    target: 'tab-8',
    type: 'navigation',
    timestamp: Date.now() - 1500000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 1500000,
  },
  {
    id: 'edge-6-9',
    source: 'tab-6',
    target: 'tab-9',
    type: 'navigation',
    timestamp: Date.now() - 1200000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 1200000,
  },
  {
    id: 'edge-8-10',
    source: 'tab-8',
    target: 'tab-10',
    type: 'navigation',
    timestamp: Date.now() - 600000,
    sessionId: 'demo-session',
    createdAt: Date.now() - 600000,
  },
];

export const demoSessions: Session[] = [
  {
    id: 'demo-session',
    name: 'Demo Session',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now(),
    nodeCount: 10,
    edgeCount: 9,
    isActive: true,
  },
  {
    id: 'session-2',
    name: 'Previous Session',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 3600000,
    nodeCount: 5,
    edgeCount: 4,
    isActive: false,
  },
];

export const demoTimeline: TimelineData = {
  sessionId: 'demo-session',
  events: [
    { type: 'node_created', timestamp: Date.now() - 3600000, data: demoNodes[0] },
    { type: 'node_created', timestamp: Date.now() - 3000000, data: demoNodes[1] },
    { type: 'edge_created', timestamp: Date.now() - 3000000, data: demoEdges[0] },
    { type: 'node_created', timestamp: Date.now() - 2800000, data: demoNodes[2] },
    { type: 'edge_created', timestamp: Date.now() - 2800000, data: demoEdges[1] },
    { type: 'node_created', timestamp: Date.now() - 2400000, data: demoNodes[3] },
    { type: 'edge_created', timestamp: Date.now() - 2400000, data: demoEdges[2] },
    { type: 'node_created', timestamp: Date.now() - 2200000, data: demoNodes[4] },
    { type: 'edge_created', timestamp: Date.now() - 2200000, data: demoEdges[3] },
    { type: 'node_created', timestamp: Date.now() - 2000000, data: demoNodes[5] },
    { type: 'edge_created', timestamp: Date.now() - 2000000, data: demoEdges[4] },
    { type: 'node_created', timestamp: Date.now() - 1800000, data: demoNodes[6] },
    { type: 'edge_created', timestamp: Date.now() - 1800000, data: demoEdges[5] },
    { type: 'node_closed', timestamp: Date.now() - 1200000, data: demoNodes[3] },
    { type: 'node_created', timestamp: Date.now() - 1500000, data: demoNodes[7] },
    { type: 'edge_created', timestamp: Date.now() - 1500000, data: demoEdges[6] },
    { type: 'node_created', timestamp: Date.now() - 1200000, data: demoNodes[8] },
    { type: 'edge_created', timestamp: Date.now() - 1200000, data: demoEdges[7] },
    { type: 'node_closed', timestamp: Date.now() - 900000, data: demoNodes[6] },
    { type: 'node_created', timestamp: Date.now() - 600000, data: demoNodes[9] },
    { type: 'edge_created', timestamp: Date.now() - 600000, data: demoEdges[8] },
  ],
  startTime: Date.now() - 3600000,
  endTime: Date.now(),
};

// Check if running in extension mode
export const isExtensionMode = (): boolean => {
  return typeof chrome !== 'undefined' && !!chrome.runtime && !!chrome.runtime.id;
};
